### ISSUE TITLE
Inconsistent title style in "Collaborate With Us" page

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#37]
The page can be found here: https://root-project.github.io/web/contribute/

The titles are using inconsistent camel case. Do we have a guideline for the website?

**Comment by Axel-Naumann** [comment]
We want camel case for titles, but we should fix them.

**Comment by couet** [comment]
seems fixed

**Comment by stwunsch** [comment]
Unfortunately it's not fixed, I am sorry! See here: https://root.cern/contribute/

![image](https://user-images.githubusercontent.com/6951222/109773076-125e9f00-7bff-11eb-9b00-75dc88e0a2e6.png)
